planner:
  name:           'BFMT'  # RRTstar or BFMT or KPIECE1
  timeout:        60      # seconds
  path_states:    5       # paths will be interpolated if they have less states than this
  save_path:      false
  display_path:   false   # if true, the planned path will be displayed in a gnuplot window

kinematics_solver:
  type:           1       # 0 - Speed, 1 - Distance, 2 - Manip1, 3 - Manip2 (Distance and Manip2 are recommended)
  timeout:        0.05    # seconds