#!/bin/sh

GREEN='\033[0;32m'
RED='\033[0;31m'

Usage()
{
    printf "Script to plot path generated by OMPL.\n\n"
    printf "Usage: $0 [-h|f]\n"
    printf "Options:\n"
    printf "h:\n\t Prints this message\n"
    printf "f:\n\t Name of file to be plotted\n"
}

if [ -z "$*" ]; then
    Usage
    exit 0
fi

while getopts ":f:h:" opt; do
    case "${opt}" in
        f)
            filename=$OPTARG
            ;;
        h)
            Usage
            exit 0
            ;;
        \?)
            printf "${RED}Unrecognised option -${OPTARG}!\n"
            printf "${RED}Available options are: [-h] [-f]\n"
            exit 0
            ;;
    esac
done

# printf "$filename\n"
if [ -z ${filename} ]; then
    printf "${RED}Invalid input!\n"
    printf "Usage: $0 -f <filename>\n"
    exit 1
elif [ ! -f "$filename" ]; then
    printf "${RED}File does not exist!\n"
    exit 1
fi

echo "Plotting $filename\n"

echo > gnuplot.in 

echo "set grid xtics ytics ztics" >> gnuplot.in
echo "set title \"OMPL Path"\" >> gnuplot.in
echo "set xlabel \"x-axis"\" >> gnuplot.in
echo "set ylabel \"y-axis"\" >> gnuplot.in
echo "set zlabel \"z-axis"\" >> gnuplot.in
echo "splot \"${filename}\" using 1:2:3 with linespoints" >> gnuplot.in
echo "pause -1 \"Press Enter or input any key to exit\"" >> gnuplot.in

gnuplot gnuplot.in

rm gnuplot.in

printf "${GREEN}Plot done!\n"
exit 0